version: '3'

services:

  # Proxy for (local) ssl termination and easier hostname access
  # SSL certificates with the virtual host name need to be added to ./data/ssl
  proxy:
    image: ghcr.io/juliushaertl/nextcloud-dev-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/ssl/:/etc/nginx/certs
    environment:
      DHPARAM_BITS: 2048
      DHPARAM_GENERATION: "false"
      HTTPS_METHOD: "noredirect"
      HSTS: "off"
    cap_add:
      - SYS_ADMIN
    networks:
      default:
        # Enable name resolution for other containers   
        # Same as /etc/hosts on Docker host
        aliases:
          - nextcloud${DOMAIN_SUFFIX_LOCAL}
          - nextcloud2${DOMAIN_SUFFIX_LOCAL}
          - nextcloud3${DOMAIN_SUFFIX_LOCAL}
          - stable24${DOMAIN_SUFFIX_LOCAL}
          - proxy${DOMAIN_SUFFIX_LOCAL}
          - hpb${DOMAIN_SUFFIX_LOCAL}
          - push${DOMAIN_SUFFIX_LOCAL}
          - keycloak${DOMAIN_SUFFIX_LOCAL}
          - portal${DOMAIN_SUFFIX_LOCAL}
          - gs1${DOMAIN_SUFFIX_LOCAL}
          - gs2${DOMAIN_SUFFIX_LOCAL}
          - lookup${DOMAIN_SUFFIX_LOCAL}

  nextcloud:
    # ADD configs/autoconfig_mysql.php configs/autoconfig_pgsql.php configs/autoconfig_oci.php configs/s3.php configs/config.php configs/redis.config.php /root/
    # ADD bin/bootstrap.sh bin/occ /usr/local/bin/
    #image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-74}:latest
    build:
      context: ./docker
      dockerfile: "./Dockerfile.php${PHP_VERSION:-74}"
    environment:
      SQL: ${SQL:-mysql}
      #	Run docker/bin/bootstrap.sh fns on container start: add_hosts; install
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      # https://github.com/nginx-proxy/nginx-proxy/blob/main/README.md#multiple-hosts
      # https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
      VIRTUAL_HOST: "nextcloud${DOMAIN_SUFFIX_LOCAL},${PUBLIC_ALIAS:-nc}${DOMAIN_SUFFIX_PUBLIC:-$DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${PUBLIC_ALIAS:-nc}${DOMAIN_SUFFIX_PUBLIC:-$DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_VIRTUAL_HOST: "nextcloud${DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_ADMIN_PASSWORD:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      # data and config are named volumes, not file system mounts
      - data:/var/www/html/data
      - config:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
      # VO Federation app mount
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/vo_federation:/var/www/html/apps-extra/vo_federation'
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      - ${DB_SERVICE:-database-mysql}
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  nextcloud2:
    build:
      context: ./docker
      dockerfile: "./Dockerfile.php${PHP_VERSION:-74}"
    environment:
      SQL: ${SQL:-mysql}
      VIRTUAL_HOST: "nextcloud2${DOMAIN_SUFFIX_LOCAL},${PUBLIC_ALIAS2:-nc2}${DOMAIN_SUFFIX_PUBLIC:-$DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${PUBLIC_ALIAS2:-nc2}${DOMAIN_SUFFIX_PUBLIC:-$DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_VIRTUAL_HOST: "nextcloud2${DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_ADMIN_PASSWORD:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data2:/var/www/html/data
      - config2:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/vo_federation:/var/www/html/apps-extra/vo_federation'
    ports:
      - "${PORTBASE:-800}1:80"
    depends_on:
      - database-mysql
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  nextcloud3:
    build:
      context: ./docker
      dockerfile: "./Dockerfile.php${PHP_VERSION:-74}"
    environment:
      SQL: ${SQL:-mysql}
      VIRTUAL_HOST: "nextcloud3${DOMAIN_SUFFIX_LOCAL},${PUBLIC_ALIAS3:-nc3}${DOMAIN_SUFFIX_PUBLIC:-$DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${PUBLIC_ALIAS3:-nc3}${DOMAIN_SUFFIX_PUBLIC:-$DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_VIRTUAL_HOST: "nextcloud3${DOMAIN_SUFFIX_LOCAL}"
      NEXTCLOUD_ADMIN_PASSWORD:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data3:/var/www/html/data
      - config3:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/vo_federation:/var/www/html/apps-extra/vo_federation'
    ports:
      - "${PORTBASE:-800}2:80"
    depends_on:
      - database-mysql
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

#  stable24:
#    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-74}:latest
#    environment:
#      SQL: 'mysql'
#      NEXTCLOUD_AUTOINSTALL: "YES"
#      NEXTCLOUD_AUTOINSTALL_APPS:
#      WITH_REDIS: "YES"
#      VIRTUAL_HOST: stable24${DOMAIN_SUFFIX_LOCAL}
#      ADDITIONAL_APPS_PATH:
#      NEXTCLOUD_TRUSTED_DOMAINS:
#    volumes:
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable24:/var/www/html'
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable24/apps-extra:/var/www/html/apps-extra'
#      - /var/www/html/data
#      - /var/www/html/config
#      - /var/www/html/apps-writable
#      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
#    depends_on:
#      - redis
#      - mail
#    extra_hosts:
#      - host.docker.internal:host-gateway

  database-mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 'nextcloud'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'
    ports:
      - "${PORTBASE:-800}6:3306"
    volumes:
      - mysql:/var/lib/mysql

#  database-postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_PASSWORD: postgres
#    expose:
#      - 5432
#    volumes:
#      - postgres:/var/lib/postgresql

  redis:
    image: redis:6

  ldap:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    expose:
      - 389
      - 636
    ports:
      - 3389:389
    environment:
      LDAP_DOMAIN: planetexpress.com
      LDAP_BASE_DN: dc=planetexpress,dc=com
    volumes:
      - ./data/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom

  phpmyadmin:
    image: phpmyadmin
    environment:
      VIRTUAL_HOST: "phpmyadmin${DOMAIN_SUFFIX_LOCAL}"
      PMA_ARBITRARY: 1
      PMA_HOST: database-mysql
      PMA_USER: root
      PMA_PASSWORD: nextcloud
    restart: always

  ldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - "${PORTBASE:-800}8:80"

  saml:
    image: unicon/simplesamlphp
    volumes:
      - ./docker/configs/var-simplesamlphp/config:/var/simplesamlphp/config
      - ./docker/configs/var-simplesamlphp/cert:/var/simplesamlphp/cert
      - ./docker/configs/var-simplesamlphp/metadata:/var/simplesamlphp/metadata
    environment:
      VIRTUAL_HOST: "sso${DOMAIN_SUFFIX_LOCAL}"
    expose:
      - 80

  mail:
    image: ghcr.io/juliushaertl/nextcloud-dev-mailhog:latest
    environment:
      VIRTUAL_HOST: "mail${DOMAIN_SUFFIX_LOCAL}"
      VIRTUAL_PORT: 8025

#  blackfire:
#    image: blackfire/blackfire:2
#    ports:
#      - 8307:8307
#    environment:
#      - BLACKFIRE_SERVER_ID
#      - BLACKFIRE_SERVER_TOKEN
#      - BLACKFIRE_CLIENT_ID
#      - BLACKFIRE_CLIENT_TOKEN
#      - BLACKFIRE_DISABLE_LEGACY_PORT=yes

#  push:
#    image: icewind1991/notify_push
#    ports:
#      - '8191:80'
#    environment:
#      RUST_LOG: debug
#      VIRTUAL_HOST: push${DOMAIN_SUFFIX_LOCAL}
#      VIRTUAL_PORT: 8191
#      DATABASE_URL: mysql://nextcloud:nextcloud@master_database-mysql_1/nextcloud
#      REDIS_URL: redis://redis
#     NEXTCLOUD_URL: https://nextcloud.local.dev.bitgrid.net

  keycloak:
    image: ${CONTAINER_KEYCLOAK:-quay.io/keycloak/keycloak:15.0.1}
    expose:
      - 8080
    volumes:
      - ./docker/configs/keycloak:/tmp/keycloak
    environment:
      VIRTUAL_HOST: "keycloak${DOMAIN_SUFFIX_LOCAL}"
      VIRTUAL_PORT: 8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: /tmp/keycloak/realm-export.json

#  portal:
#    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-74}:latest
#    environment:
#      VIRTUAL_HOST: portal${DOMAIN_SUFFIX_LOCAL}
#      SQL: 'mysql'
#      GS_MODE: master
#    volumes:
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/server:/var/www/html'
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/server/apps-extra:/var/www/html/apps-extra'
#      - /var/www/html/data
#      - /var/www/html/config
#      - ./data/skeleton/:/skeleton
#      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
#    depends_on:
#      - proxy
#      - database-mysql
#      - lookup
#      - redis
#      - mail
#    extra_hosts:
#      - host.docker.internal:host-gateway

#  gs1:
#    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-74}:latest
#    environment:
#      VIRTUAL_HOST: gs1${DOMAIN_SUFFIX_LOCAL}
#      SQL: 'mysql'
#      GS_MODE: slave
#    volumes:
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/server:/var/www/html'
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/server/apps-extra:/var/www/html/apps-extra'
#      - /var/www/html/data
#      - /var/www/html/config
#      - ./data/skeleton/:/skeleton
#      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
#    depends_on:
#      - proxy
#      - portal
#      - database-mysql
#      - lookup
#      - redis
#      - mail
#    extra_hosts:
#      - host.docker.internal:host-gateway

#  gs2:
#    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-74}:latest
#    environment:
#      VIRTUAL_HOST: gs2${DOMAIN_SUFFIX_LOCAL}
#      SQL: 'mysql'
#      GS_MODE: slave
#    volumes:
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/server:/var/www/html'
#      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/server/apps-extra:/var/www/html/apps-extra'
#      - /var/www/html/data
#      - /var/www/html/config
#      - ./data/skeleton/:/skeleton
#      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
#    depends_on:
#      - proxy
#      - portal
#      - database-mysql
#      - lookup
#      - redis
#      - mail
#    extra_hosts:
#      - host.docker.internal:host-gateway

#  lookup:
#    image: ghcr.io/juliushaertl/nextcloud-dev-lookupserver:latest
#    environment:
#      VIRTUAL_HOST: "lookup${DOMAIN_SUFFIX_LOCAL}"
#    # volumes:
#    #  - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/lookupserver:/var/www/html'
#    extra_hosts:
#      - host.docker.internal:host-gateway


volumes:
  data:
  config:
  mysql:
#  postgres:
  data2:
  config2:
  data3:
  config3:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-192.168.21.0/24}
